# example of docker-compose file 

services:
  whisper:
    image: franc2002/wyoming-whisper-cpp:vulkan
    container_name: wyoming-whisper
    restart: unless-stopped
    group_add:
      - video
    volumes:
      - whisper-data:/data
    command:
      - --language
      - en
      - --model
      - large-v3-turbo-q5_0

    ports:
      - 10300:10300
    devices:
      - "/dev/dri" # pass through GPU device, needed for vulkan and rocm
      - "/dev/kfd" # pass through GPU device, needed for rocm

volumes:
  whisper-data:
